name: Build and push images

on:
    push:
        branches: [main]
    workflow_dispatch:

permissions:
    # Allow runner to check out code
    contents: read
    # Allow runner to push images to GHCR under my account
    packages: write

jobs:
    test:
        # Pick machine type
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              # Pulls code into the machine
              uses: actions/checkout@v6

            - name: Set up Go
              #Installs go into the machine
              uses: actions/setup-go@v6
              with:
                #Installs whatever go version is in the projects go.mod file
                go-version-file: go.mod
                # No downloaded modules, nothing to cache, project only uses standard library
                cache: false

            - name: Run go vet
              run: go vet ./...

            - name: Run unit tests
              run: go test ./...

    build-and-push:
        #Make this job wait, and only start if test has passed
        needs: test
        # This is a fresh runner, so machine and checkout are set all over again
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Set up Docker Buildx
              # Installs Buildx, Docker's newer builder
              uses: docker/setup-buildx-action@v4

            - name: Log in to GHCR
              #Login to GitHub Container Registry
              uses: docker/login-action@v4
              with:
                registry: ghcr.io
                # github.actor is the username of whoever triggered the run
                username: ${{ github.actor }}
                # Automatic per-run token, GitHube injects it, this is where packages: write permission gets used
                password: ${{ secrets.GITHUB_TOKEN }}
